#!/bin/bash
NAME=postgresql
SCOPE=$HOME/.docker/$NAME
mkdir -p $SCOPE

IMAGE="sameersbn/postgresql:latest"

function ContainerIsRunning() {
  test $(echo -e "GET /containers/$1/json HTTP/1.0\r\n" | sudo nc -U /var/run/docker.sock | grep HTTP | awk '{ print $2 }') -eq 200
}

ContainerIsRunning "postgresql" || {
  sudo docker run --name postgresql -d \
    -v /opt/postgresql/data:/var/lib/postgresql $IMAGE
  sleep 5 # TODO Wait for it to startup, do this via a loop though
  PG_IP=$(sudo docker inspect postgresql | grep IPAddres | awk -F'"' '{print $4}')
  sudo docker logs postgresql > $SCOPE/info
  echo "Connect with psql -U postgres -h $PG_IP" >> $SCOPE/info
}

cat $SCOPE/info
